server:
  port: 8087

spring:
  application:
    name: API-GATEWAY
  
  cloud:
    gateway:
      routes:
            
        - id: EMPLOYEE-SERVICE
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - AuthenticationFilter
          
          
        - id: PROJECT-SERVICE
          uri: lb://project-service
          predicates:
            - Path=/Project/**
          filters:
            - AuthenticationFilter
          

eureka:
  instance:
    
    client:
      fetch-registry: true
      prefer-ip-address: true
      register-with-eureka: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      spring:
  main:
    web-application-type: servlet
   
    allow-bean-definition-overriding: true
      


