server:
  port: 8087
eureka:
  instance:
    client:
      fetch-registry: true
      prefer-ip-address: true
      register-with-eureka: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
      - id: admin
        uri: http://localhost:8080/
        predicates:
        - Path=/admin/**
        
        - id: TASK-SERVICE
          uri: lb://task-service
          predicates:
        - Path=/task/**
        
        - id: team
          uri: http://localhost:8085/
          predicates:
        - Path=/team/**
        
        - id: PROJECT-SERVICE
          uri: http://localhost:8082/project_service
          predicates:
        - Path=/project/**
        